Repository Azure/pcs-remote-monitoring-webui, pull requests merged in 2018-05, with the labels that each got.

#968 Fix issue on the maintenance page where it wouldn't update correctly …
  src/components/pages/maintenance/maintenance.container.js
  src/components/pages/maintenance/maintenance.js
  src/components/pages/rules/rulesGrid/rulesGrid.scss
  src/components/shared/forms/radio.js
Labels: Maintenance, bug

#971 Fix stroke color for disabled icon on grid row hover/focus
  src/assets/icons/disabled.svg
  src/components/shared/cellRenderers/cellRenderer.scss
Labels: bug

#980 Fix issue in the maintenance page refresh button
  src/components/pages/maintenance/maintenance.js
Labels: bug

#982 Fix grid columns order on page resize
  src/components/pages/devices/devicesGrid/devicesGridConfig.js
  src/components/pages/rules/rulesGrid/rulesGridConfig.js
  src/components/shared/pcsGrid/pcsGrid.scss
  src/components/shared/pcsGrid/pcsGridConfig.js
Labels: bug

#983 Update azure maps messaging
  public/locales/en/translations.json
  src/components/pages/dashboard/panels/map/mapPanel.js
Labels: bug

#985 Show a message over the analytics panel if no data is available
  src/components/pages/dashboard/panels/analytics/analyticsPanel.js
  src/components/pages/maintenance/ruleDetails/ruleDetails.js
Labels: bug

#986 Fix selected radio btn style
  src/components/shared/forms/styles/radio.scss
  src/styles/_themes.scss
Labels: bug

#990 Temp fix for context buttons on the maintenance page
  src/components/pages/maintenance/ruleDetails/ruleDetails.js
  src/store/rootReducer.js
Labels: bug

#992 Add popup on the map to show the device id
  src/components/pages/dashboard/panels/map/mapPanel.js
  src/components/pages/dashboard/panels/map/mapPanel.scss
  src/styles/_themes.scss
Labels: Dashboard

#994 Fix multi selection on the alert grid
  src/components/pages/maintenance/ruleDetails/ruleDetails.js
Labels: bug

#1000 Fix minor issue in the validation
  src/utilities/validation.js
Labels: bug

#1001 Remove remaining contrast based theme colors
  src/components/shared/forms/styles/formControl.scss
  src/styles/_themes.scss
Labels: bug

#1002 Fix state binding for jobName
  src/components/pages/devices/flyouts/deviceJobs/deviceJobProperties.js
  src/components/pages/devices/flyouts/deviceJobs/deviceJobTags.js
Labels: bug

#1005 Move Azure map initialization to a seperate component
  src/components/pages/dashboard/panels/map/azureMap.js
  src/components/pages/dashboard/panels/map/mapPanel.js
Labels: bug

#1006 Remove console.log
  src/components/pages/dashboard/panels/map/mapPanel.js
Labels: bug

#1007 Never update the azureMap component
  src/components/pages/dashboard/panels/map/azureMap.js
  src/components/pages/dashboard/panels/map/mapPanel.js
Labels: enhancement

#1008 Open device details from map
  src/components/pages/dashboard/panels/map/mapPanel.js
  src/components/pages/dashboard/panels/map/mapPanel.scss
Labels: Dashboard

#1010 Clear the maintenance context menu when the refresh button is clicked
  src/components/pages/maintenance/ruleDetails/ruleDetails.js
  src/components/pages/rules/flyouts/ruleEditor/ruleEditor.js
  src/components/shared/forms/formLabel.js
Labels: bug

#1017 Add indicator to maintenance page
  src/components/pages/maintenance/ruleDetails/ruleDetails.js
  src/components/pages/maintenance/ruleDetails/ruleDetails.scss
  src/components/shared/refreshBar/refreshBar.scss
Labels: Maintenance, enhancement

#1013 Add question icon on the header
  public/locales/en/translations.json
  src/assets/icons/questionMark.svg
  src/components/app/header/header.js
  src/components/app/header/header.scss
  src/components/app/navigation/navigation.js
  src/utilities/svgs.js
Labels: enhancement

#1023 PCS grid refactor
  package.json
  src/components/pages/dashboard/dashboard.scss
  src/components/pages/dashboard/grid/grid.scss
  src/components/pages/dashboard/panel/panel.scss
  src/components/pages/dashboard/panels/alerts/alertsPanel.js
  src/components/pages/devices/devices.scss
  src/components/pages/devices/devicesGrid/devicesGrid.js
  src/components/pages/devices/devicesGrid/devicesGridConfig.js
  src/components/pages/devices/flyouts/deviceDetails/deviceDetails.js
  src/components/pages/maintenance/grids/alertOccurrencesGrid.js
  src/components/pages/maintenance/jobDetails/jobDetails.js
  src/components/pages/maintenance/maintenance.scss
  src/components/pages/maintenance/ruleDetails/ruleDetails.js
  src/components/pages/maintenance/ruleDetails/ruleDetails.scss
  src/components/pages/rules/rules.scss
  src/components/pages/rules/rulesGrid/rulesGrid.js
  src/components/pages/rules/rulesGrid/rulesGridConfig.js
  src/components/shared/cellRenderers/cellRenderer.scss
  src/components/shared/cellRenderers/countRenderer/countRenderer.js
  src/components/shared/cellRenderers/index.js
  src/components/shared/cellRenderers/isSimulatedRenderer/isSimulatedRenderer.js
  src/components/shared/cellRenderers/lastTriggerRenderer/lastTriggerRenderer.js
  src/components/shared/cellRenderers/softSelectLinkRenderer/softSelectLinkRenderer.js
  src/components/shared/pageContent/pageContent.scss
  src/components/shared/pcsGrid/pcsGrid.js
  src/components/shared/pcsGrid/pcsGrid.scss
  src/components/shared/pcsGrid/pcsGridConfig.js
  src/styles/_mixins.scss
  src/styles/_themes.scss
  src/styles/_variables.scss
Labels: enhancement

#1019 Changed pivot bar color
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  package-lock.json
  src/styles/_themes.scss
Labels: bug

#1025 Add device and rule grid filter inputs
  public/locales/en/translations.json
  src/components/pages/dashboard/panels/alerts/alertsPanel.js
  src/components/pages/dashboard/panels/map/mapPanel.scss
  src/components/pages/devices/devices.js
  src/components/pages/devices/flyouts/deviceDelete/deviceDelete.scss
  src/components/pages/devices/flyouts/deviceDetails/deviceDetails.scss
  src/components/pages/devices/flyouts/deviceDetails/propertyGrid/propertyGrid.scss
  src/components/pages/devices/flyouts/deviceJobs/deviceJobs.scss
  src/components/pages/devices/flyouts/deviceNew/deviceNew.scss
  src/components/pages/maintenance/maintenance.scss
  src/components/pages/maintenance/ruleDetails/ruleDetails.scss
  src/components/pages/rules/flyouts/ruleStatus/ruleStatus.scss
  src/components/pages/rules/rules.js
  src/components/pages/rules/rulesGrid/rulesGrid.js
  src/components/shared/contextMenu/index.js
  src/components/shared/contextMenu/searchInput/searchInput.js
  src/components/shared/contextMenu/searchInput/searchInput.scss
  src/components/shared/index.js
  src/styles/_themes.scss
Labels: bug, enhancement
